const sources = {
  gdpr: ['GDPR — Regulation (EU) 2016/679', 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679'],
  privacy: ['EU: Data protection and online privacy', 'https://europa.eu/youreurope/citizens/consumers/internet-telecoms/data-protection-online-privacy/index_en.htm'],
  cookies: ['EU: Online privacy and cookies', 'https://europa.eu/youreurope/business/growing/digitalising/online-privacy/index_en.htm'],
  cookieOpinion: ['Article 29 Working Party: Opinion 04/2012 on cookie consent exemption', 'https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf'],
  business: ['2001. évi CVIII. törvény, 4. §', 'https://njt.jog.gov.hu/jogszabaly/2001-108-00-00'],
  civil: ['2013. évi V. törvény, 2:48. §', 'https://njt.jog.gov.hu/jogszabaly/2013-5-00-00'],
  consumer: ['45/2014. (II. 26.) Korm. rendelet', 'https://njt.jog.gov.hu/jogszabaly/2014-45-20-22'],
  complaints: ['1997. évi CLV. törvény, 17/A. §', 'https://njt.jog.gov.hu/jogszabaly/1997-155-00-00'],
  board: ['Budapesti Békéltető Testület — elérhetőségek', 'https://bekeltet.bkik.hu/elerhetosegek'],
  retention: ['European Commission — GDPR principles', 'https://commission.europa.eu/law/law-topic/data-protection/information-business-and-organisations/principles-gdpr_en'],
  naih: ['NAIH — contact / complaints', 'https://www.naih.hu/ugyfelszolgalat-kapcsolat'],
  wcag: ['W3C: Web Content Accessibility Guidelines 2.2', 'https://www.w3.org/TR/WCAG22/'],
  accessibility: ['EU: Accessibility of products and services', 'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=legissum:4403933'],
}

export const legalContent = {
  en: {
    privacy: {
      title: 'Privacy policy',
      sections: [
        ['What this website processes', 'This portfolio has no checkout, advertising pixels, analytics code or embedded social feeds. Public photographs and approved reviews are loaded from the website and its gallery service. Servers necessarily receive connection data such as IP address, requested URL and browser information. Hosting and email provider identities, log periods and any international transfers must be confirmed above before this draft is published.'],
        ['Contact enquiries', 'The contact form prepares a draft in your own email application. It does not submit to a website database and does not send the email automatically. Your optional name and message remain in page memory until you leave; your email address and any other details are received when you send the email. Do not include identity documents, sensitive information or details about other people unless needed.', 'Enquiries about a booking are handled to take steps at your request before a contract (Article 6(1)(b)). Other correspondence is handled for the legitimate interest of answering a request (Article 6(1)(f)). A compulsory marketing or privacy-consent checkbox is not used. The proposed retention for enquiries that do not lead to a booking is six months after the final reply; this mailbox schedule still needs owner approval and configuration.'],
        ['Reviews and publication', 'Submitting a review sends its text, chosen display name, optional event/location and publication permission to our PocketBase service at Hetzner in Germany. It is submitted as hidden for administrator review. An unticked permission box asks specifically to publish those supplied details. You may use a first name or nickname; event/location is optional. Review publication is separate from booking a service and is based on consent (Article 6(1)(a)). No email address is requested in this form. Rejected reviews should be deleted within 30 days of the moderation decision; this operational schedule still needs configuration. Reviews are manually checked before publication; identity or purchase verification is not claimed.', 'Ask info@prismvisuals.hu to withdraw publication permission, identifying the review without sending unnecessary identity documents. Withdrawal does not make earlier lawful use unlawful. Remove the public review on withdrawal; any restricted evidence retained for a genuine dispute needs its own justified period.'],
        ['Client photographs and portfolios', 'The client-gallery route is temporarily unavailable while secure delivery is reviewed. Photography, editing and agreed delivery for a contracting client may rely on the service contract where necessary. Other people in photographs are not automatically covered by that contract. Their image rights and the appropriate data-protection basis must be handled separately.', 'Portfolio or social-media publication is a separate purpose. Owning copyright in a photograph does not give unlimited permission to publish the people in it. Public use, private delivery and optional extended archiving must be distinguished; children require particular care and appropriate representative permission. Delivery does not create a right to keep photographs indefinitely.'],
        ['Recipients, safeguards and retention', 'Only people and providers needed to answer enquiries, perform the agreed service, maintain the website or meet legal duties should receive data. Provider contracts, locations and transfer safeguards remain unverified. No sale of visitor data, advertising profiles or automated decisions are implemented in this website.', 'Full client galleries and their backups are to be kept for one year after delivery, then deleted. The deletion process must be configured before client uploads resume. Any genuine legal hold must be documented and limited; selected portfolio references require separate permission where applicable. Accounting and legally required records follow their applicable obligations; those obligations do not automatically justify keeping every photograph.'],
        ['Your choices and rights', 'Contact info@prismvisuals.hu to request access, correction, deletion, restriction, portability where applicable, or to object to processing based on legitimate interests. Requests are normally answered within one month; any lawful extension must be explained. Consent can be withdrawn. You may complain to the Hungarian data protection authority (NAIH) or seek a judicial remedy. NAIH’s official contact page is linked below.'],
      ],
      sources: [sources.gdpr, sources.privacy, sources.civil, sources.naih, sources.retention],
    },
    terms: {
      title: 'Website terms & service information',
      sections: [
        ['Using the website', 'Prism Visuals presents photography and videography work. Browsing or sending an enquiry does not itself make a booking or take a payment. A service requires a separate agreement covering scope, price including applicable taxes, dates, delivery, usage rights and cancellation. These website terms do not replace that agreement.'],
        ['Quotes, cancellations and refunds', 'There is no online purchase or payment facility here, so there is no website checkout refund process. Contact info@prismvisuals.hu about an existing booking. Any refund depends on the separate agreement and mandatory consumer law; no blanket “non-refundable” rule is imposed here.', 'A contract concluded by email or telephone can still be a distance contract. Where statutory withdrawal rules apply, a consumer generally has 14 days from concluding a service contract. Starting work early and loss of withdrawal rights require the applicable express requests, acknowledgements and confirmation. Exceptions must be assessed for the actual service; a custom photograph or a wedding date does not automatically remove all rights. Mandatory consumer rights remain unaffected.'],
        ['Photographs and permitted use', 'The photographer retains copyright except where agreed otherwise or required by law. Client use follows the agreed licence. Website display does not grant a general licence for commercial copying, resale or redistribution; statutory exceptions remain available. Access to a private delivery link does not itself grant permission to publish other people’s images.'],
        ['Enquiries, reviews and links', 'Do not send unlawful material or disclose another person’s private details in a review. Reviews are manually moderated and should describe your own experience. External social links take you to services with their own privacy terms; no social feed is embedded here.'],
        ['Complaints and disputes', 'Send a complaint to info@prismvisuals.hu and describe the service and requested resolution. Complaints may also be sent to the registered address in Business details. Written consumer complaints are answered within 30 days; complaint records and responses are kept for three years under Hungarian consumer-protection law. The Budapest Conciliation Board can be contacted at 1016 Budapest, Krisztina krt. 99.; postal address: 1253 Budapest, Pf. 10.; email: bekelteto.testulet@bkik.hu. The consumer’s place of residence can determine the competent board. This page does not restrict access to a court, a consumer authority or a competent conciliation body. No obsolete EU online-dispute-resolution platform link is used.'],
      ],
      sources: [sources.consumer, sources.business, sources.civil, sources.complaints, sources.board],
    },
    cookies: {
      title: 'Cookie and browser-storage policy',
      sections: [
        ['Current website configuration', 'This version contains no analytics, marketing cookies, tracking pixels or third-party embeds. Fonts are served locally. Unconfirmed Instagram and Facebook links have been removed; no social content is embedded.', 'No optional cookie-consent banner is included because no optional tracking is enabled in this version. This conclusion is conditional on the deployed hosting/CDN configuration also avoiding optional tracking. Consent must be obtained before introducing analytics, advertising or other non-essential storage/access. A privacy notice alone is not consent.'],
        ['Storage used for requested functions', 'language: session storage, set only when you select a language, to retain that choice within the tab session. pocketbase_auth: session storage for an administrator’s requested sign-in; cleared by logout or the end of the tab session. Administrative gallery cover choices use session keys beginning gallery_cover_. These are not advertising identifiers.', 'The client-gallery login and guest-registration screens are not enabled. This version no longer reads their old persistent login flags, guest tokens or review cache. Older local storage may remain on your device until you clear website data in your browser.'],
        ['Control and duration', 'Session storage normally ends with the tab session; browser restore features may restore it. Log out of an administrator session, especially on a shared device. You can clear or block website storage through your browser settings; sign-in or language persistence may then stop working. The website itself does not set JavaScript cookies, but hosting response headers and infrastructure must be checked separately before publication.'],
      ],
      sources: [sources.cookies, sources.cookieOpinion],
    },
    business: {
      title: 'Business details / legal notice',
      sections: [
        ['Business status', 'Prism Visuals is the website brand. The owner confirms that Iszak Gábor Adrián E.V is an operating sole trader. The registration number and the missing statutory details above still need completion. Budapest is a service location, not a substitute for a registered address.'],
        ['Before making a booking', 'Request a written quote and the confirmed operator details. This site does not accept online payments or automatically confirm bookings. Provider and business information on this draft must be completed before publication as a final legal notice.'],
      ],
      sources: [sources.business],
    },
    accessibility: {
      title: 'Accessibility information',
      sections: [
        ['Using this website', 'Keyboard users can skip the navigation, see focus indicators, open galleries and close dialogs with Escape. The language switch updates the page language. Form fields have labels, and feedback is announced. Motion preferences are respected and the homepage slideshow has a pause control.'],
        ['Ongoing work', 'WCAG 2.2 AA is the implementation target, not a certification. Dynamic gallery image descriptions depend on the supplied descriptions; fallback labels cannot convey every visual detail. A complete screen-reader, zoom, mobile-assistive-technology and production-content audit has not been completed.'],
        ['Report a barrier', 'Email info@prismvisuals.hu with the page and the difficulty you encountered. You can request information or arrange an enquiry by email if a website interaction is inaccessible. Please send only details needed to understand the problem.'],
      ],
      sources: [sources.wcag, sources.accessibility],
    },
  },
  hu: {
    privacy: {
      title: 'Adatkezelési tájékoztató',
      sections: [
        ['A weboldalon kezelt adatok', 'A portfólióoldalon nincs fizetési felület, analitikai kód, hirdetési képpont vagy beágyazott közösségi hírfolyam. A nyilvános fényképek és jóváhagyott értékelések az oldalról és a galériaszolgáltatásból töltődnek be. A kiszolgálók a kapcsolathoz szükséges adatokat, például IP-címet, kért URL-t és böngészőadatokat kapnak. A szolgáltatók, naplózási idők és esetleges nemzetközi adattovábbítások adatait a végleges közzététel előtt tisztázni kell.'],
        ['Kapcsolatfelvétel', 'Az űrlap a saját levelezőalkalmazásodban készít levéltervezetet. Nem küld adatot webes adatbázisba és nem küldi el automatikusan a levelet. A nem kötelező név és az üzenet az oldal elhagyásáig a lap memóriájában marad; az e-mail-címedet és a levél tartalmát elküldéskor kapjuk meg. Ne adj meg okmányadatot, különleges adatot vagy mások személyes adatait, ha nem szükséges.', 'A szolgáltatás iránti érdeklődés kezelése a kérésedre történő szerződéskötés előtti lépésekhez szükséges (6. cikk (1) b)); más megkereséseknél a válaszadáshoz fűződő jogos érdek lehet a jogalap (6. cikk (1) f)). Ehhez nem kérünk kötelező marketing- vagy adatkezelési hozzájárulást. A megrendeléshez nem vezető érdeklődések javasolt megőrzése az utolsó választól számított hat hónap; a levelezési törlési rend jóváhagyása és beállítása még szükséges.'],
        ['Értékelések közzététele', 'Beküldéskor az értékelés, a választott név, a nem kötelező esemény/helyszín és a közzétételi engedély a németországi Hetznernél tárolt PocketBase rendszerünkbe kerül. Az értékelés rejtetten vár adminisztrátori ellenőrzésre. Egy alapból üres jelölőnégyzet külön engedélyt kér a megadott adatok közzétételére. Keresztnév vagy becenév is használható; az esemény és helyszín megadása nem kötelező. A közzététel hozzájáruláson alapul (6. cikk (1) a)), és nem feltétele a szolgáltatás igénybevételének. Az űrlap nem kér e-mail-címet. Az elutasított értékeléseket a döntéstől számított 30 napon belül törölni kell; e törlési rend beállítása még szükséges. Az értékeléseket kézzel ellenőrizzük; nem állítjuk, hogy minden értékelő személyazonossága vagy vásárlása igazolt.', 'A közzétételi engedély az info@prismvisuals.hu címen vonható vissza, az értékelés azonosításával. A visszavonás a korábbi jogszerű kezelést nem érinti. A nyilvános értékelést visszavonáskor el kell távolítani; tényleges jogvita bizonyítékának korlátozott megőrzéséhez külön indokolt határidő kell.'],
        ['Ügyfélképek és portfólió', 'Az ügyfélgaléria a biztonságos kézbesítés felülvizsgálatáig nem érhető el. A szerződő ügyfél részére szükséges fotózás, szerkesztés és vállalt átadás a szerződés teljesítésén alapulhat. A képeken szereplő más személyekre az ügyfél szerződése nem terjed ki automatikusan; képmásjogaikat és az adatkezelés megfelelő jogalapját külön rendezni kell.', 'A portfólióban vagy közösségi oldalon történő közzététel külön cél. A fotó szerzői joga önmagában nem ad korlátlan engedélyt a rajta szereplők képmásának közzétételére. A nyilvános felhasználást, magáncélú átadást és választható hosszabb archiválást külön kell kezelni; gyermekeknél különös körültekintés és megfelelő képviselői engedély szükséges. Az átadás nem teszi jogszerűvé a korlátlan megőrzést.'],
        ['Címzettek és megőrzés', 'Adatot csak a megkeresés, a vállalt szolgáltatás, a weboldal működtetése vagy jogi kötelezettség teljesítéséhez szükséges személyek és szolgáltatók kaphatnak. A szolgáltatói szerződések, országok és adattovábbítási garanciák még nem ellenőrzöttek. Az oldal nem valósít meg adatértékesítést, hirdetési profilalkotást vagy automatizált döntéshozatalt.', 'A teljes ügyfélgalériát és biztonsági másolatait az átadástól számított egy évig őrizzük, majd törölni kell őket. A törlési folyamatot a feltöltés újraindítása előtt be kell állítani. Tényleges jogi megőrzés csak dokumentált és korlátozott lehet; a kiválasztott portfólióképekhez szükség esetén külön engedély kell. A számviteli és más kötelező iratokra saját megőrzési szabályaik vonatkoznak; ezek nem indokolják automatikusan valamennyi fénykép tárolását.'],
        ['Érintetti jogok', 'Az info@prismvisuals.hu címen hozzáférést, helyesbítést, törlést, korlátozást és – feltételei fennállásakor – adathordozhatóságot kérhetsz; jogos érdeken alapuló kezelés ellen tiltakozhatsz. A válaszadás főszabály szerint egy hónapon belül történik; jogszerű hosszabbítás esetén indokolást kell adni. Hozzájárulásodat visszavonhatod. Panaszt tehetsz a NAIH-nál, vagy bírósághoz fordulhatsz. A NAIH hivatalos elérhetősége lent található.'],
      ],
      sources: [sources.gdpr, sources.privacy, sources.civil, sources.naih, sources.retention],
    },
    terms: {
      title: 'Felhasználási feltételek és szolgáltatási tájékoztató',
      sections: [
        ['A weboldal használata', 'A Prism Visuals fotós és videós munkákat mutat be. Az oldal böngészése vagy megkeresés küldése önmagában nem foglalás és nem jár fizetéssel. A szolgáltatáshoz külön megállapodás szükséges a feladatról, adókat is tartalmazó díjról, időpontokról, átadásról, felhasználási jogokról és lemondásról. E weboldalfeltételek ezt nem helyettesítik.'],
        ['Árajánlat, lemondás, visszatérítés', 'Az oldalon nincs online vásárlás vagy fizetés, ezért webes pénztári visszatérítési folyamat sincs. Meglévő foglalásoddal kapcsolatban az info@prismvisuals.hu címen érdeklődhetsz. A visszatérítést az egyedi megállapodás és a kötelező fogyasztóvédelmi szabályok határozzák meg; itt nem írunk elő általános „nem visszatérítendő” szabályt.', 'E-mailben vagy telefonon kötött szerződés is lehet távollévők közötti szerződés. Ha az elállási szabályok alkalmazandók, szolgáltatásnál főszabály szerint a szerződéskötéstől számított 14 nap áll rendelkezésre. A korai teljesítéshez és az elállási jog elvesztéséhez a jogszabály szerinti kifejezett kérés, tudomásulvétel és visszaigazolás szükséges. A kivételeket az adott szolgáltatásra kell megvizsgálni; az egyedi fénykép vagy az esküvő időpontja önmagában nem szüntet meg minden jogot. A kötelező fogyasztói jogokat e tájékoztató nem korlátozza.'],
        ['Fényképek és felhasználás', 'Eltérő megállapodás vagy jogszabály hiányában a szerzői jogok a fotóst illetik. Az ügyfél felhasználási lehetőségeit a megállapodás rendezi. A webes megjelenítés nem ad általános engedélyt kereskedelmi másolásra, továbbértékesítésre vagy terjesztésre; a törvényi kivételek érvényesülnek. Egy privát átadási link nem jelent önmagában engedélyt mások képmásának közzétételére.'],
        ['Megkeresések, értékelések és külső linkek', 'Ne küldj jogellenes tartalmat, és értékelésben ne közöld mások magánadatait. Az értékelés saját tapasztalatról szóljon; megjelenés előtt kézi ellenőrzés történik. A közösségi linkek külön adatkezelési feltételekkel működő szolgáltatásokra vezetnek; az oldal nem ágyaz be közösségi hírfolyamot.'],
        ['Panaszkezelés', 'Panaszodat az info@prismvisuals.hu címre küldheted, a szolgáltatás és az igényelt megoldás leírásával. Panasz az Impresszumban megadott székhelyre is küldhető. Az írásbeli fogyasztói panaszt 30 napon belül megválaszoljuk; a panaszt és a választ három évig őrizzük a fogyasztóvédelmi törvény szerint. Budapesti Békéltető Testület: 1016 Budapest, Krisztina krt. 99.; levelezési cím: 1253 Budapest, Pf. 10.; e-mail: bekelteto.testulet@bkik.hu. Az illetékességet a fogyasztó lakóhelye is meghatározhatja. Ez az oldal nem korlátozza a bírósághoz, fogyasztóvédelmi hatósághoz vagy békéltető testülethez fordulást. Megszűnt uniós online vitarendezési platformra nem hivatkozunk.'],
      ],
      sources: [sources.consumer, sources.business, sources.civil, sources.complaints, sources.board],
    },
    cookies: {
      title: 'Süti- és böngészőtárhely-tájékoztató',
      sections: [
        ['Az oldal jelenlegi működése', 'Ebben a változatban nincs analitika, marketingcélú süti, követő képpont vagy külső beágyazás. A betűtípusok helyben tároltak. A még nem megerősített Instagram- és Facebook-linkeket eltávolítottuk; közösségi tartalom nincs beágyazva.', 'Nem került be opcionális sütiket engedélyező sáv, mert ebben a változatban nincs opcionális követés. Ez csak akkor helytálló az éles oldalon is, ha a tárhely/CDN beállításai sem tesznek hozzá ilyet. Analitika, hirdetés vagy más nem szükséges tárolás/hozzáférés bevezetése előtt hozzájárulás szükséges. A tájékoztató nem helyettesíti a hozzájárulást.'],
        ['Kért funkciókhoz használt tárhely', 'language: munkamenet-tárhely, csak nyelvválasztáskor mentve, hogy a választás a böngészőlap munkamenetében megmaradjon. pocketbase_auth: az adminisztrátor kért bejelentkezésének munkamenet-tárhelye, kijelentkezéskor vagy a lap munkamenetének végén törlődik. Az adminisztrátori borítóképválasztás gallery_cover_ kezdetű munkamenetkulcsot használ. Ezek nem hirdetési azonosítók.', 'Az ügyfélgaléria bejelentkezése és vendégregisztrációja nem aktív. Ez a változat nem olvassa a korábbi tartós galériabelépési jelzőket, vendégtokeneket vagy értékelési gyorsítótárat. Régi helyi adatok az eszközön maradhatnak, amíg a böngészőben nem törlöd a webhely adatait.'],
        ['Beállítások és időtartam', 'A munkamenet-tárhely rendszerint a lap munkamenetével megszűnik; a böngésző visszaállítási funkciója visszaállíthatja. Közös eszközön különösen fontos az adminisztrátori kijelentkezés. A böngészőben a tárhely törölhető vagy letiltható; emiatt a belépés vagy a nyelvválasztás megjegyzése nem feltétlenül működik. Az oldal nem állít be JavaScript-sütit, de az infrastruktúra válaszfejléceit külön ellenőrizni kell a közzététel előtt.'],
      ],
      sources: [sources.cookies, sources.cookieOpinion],
    },
    business: {
      title: 'Impresszum',
      sections: [
        ['A vállalkozás állapota', 'A Prism Visuals a weboldal márkaneve. Az üzemeltető megerősítette, hogy Iszak Gábor Adrián E.V működő egyéni vállalkozás. A nyilvántartási számot és a fent hiányzó kötelező adatokat még pótolni kell. Budapest szolgáltatási helyszín, nem helyettesíti a székhely pontos címét.'],
        ['Megrendelés előtt', 'Kérj írásos ajánlatot és megerősített szolgáltatói adatokat. Az oldal nem fogad online fizetést és nem igazol vissza automatikusan foglalást. A tervezet üzleti és szolgáltatói adatait végleges jogi tájékoztatóként való közzététel előtt ki kell egészíteni.'],
      ],
      sources: [sources.business],
    },
    accessibility: {
      title: 'Akadálymentességi tájékoztató',
      sections: [
        ['Az oldal használata', 'Billentyűzettel átugorható a navigáció, látható a fókusz, megnyithatók a galériák, és Escape-pel bezárhatók a párbeszédablakok. A nyelvváltás az oldal nyelvi jelölését is módosítja. Az űrlapokhoz címkék és felolvasott visszajelzések tartoznak. A csökkentett mozgás beállítást figyelembe vesszük, a főoldali diavetítés szüneteltethető.'],
        ['Folyamatban lévő munka', 'A WCAG 2.2 AA megvalósítási cél, nem tanúsítvány. A dinamikus galériák képleírása a megadott szövegtől függ; a helyettesítő címkék nem közvetítenek minden vizuális részletet. Teljes képernyőolvasós, nagyításos, mobil segítőtechnológiai és éles tartalmi audit még nem történt.'],
        ['Akadály jelzése', 'Az info@prismvisuals.hu címen jelezheted az érintett oldalt és a tapasztalt nehézséget. Ha valamely művelet nem hozzáférhető, e-mailben is kérhetsz információt vagy egyeztetést. Csak a probléma megértéséhez szükséges adatokat küldd el.'],
      ],
      sources: [sources.wcag, sources.accessibility],
    },
  },
}
